import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { Check } from "lucide-react";
import { CaseStudyCard } from "@/components/home/case-study-card";
import { ButtonLink } from "@/components/ui/button";
import { Icon } from "@/components/ui/icon";
import Link from "@/components/ui/link";
import { Breadcrumbs, Faq, JsonLd } from "@/components/ui/misc";
import { PageCta } from "@/components/ui/page-cta";
import { Container, PageHero, SectionHeader } from "@/components/ui/section";
import { solutions } from "@/content/solutions";
import { site } from "@/content/site";